var files_dup =
[
    [ "aCommand.c", "a_command_8c.html", "a_command_8c" ],
    [ "aCommand.h", "a_command_8h.html", "a_command_8h" ],
    [ "cCommand.c", "c_command_8c.html", "c_command_8c" ],
    [ "cCommand.h", "c_command_8h.html", "c_command_8h" ],
    [ "clients.c", "clients_8c.html", "clients_8c" ],
    [ "clients.h", "clients_8h.html", "clients_8h" ],
    [ "dCommand.c", "d_command_8c.html", "d_command_8c" ],
    [ "dCommand.h", "d_command_8h.html", "d_command_8h" ],
    [ "fCommand.c", "f_command_8c.html", "f_command_8c" ],
    [ "fCommand.h", "f_command_8h.html", "f_command_8h" ],
    [ "genericFunctions.c", "generic_functions_8c.html", "generic_functions_8c" ],
    [ "global.h", "global_8h.html", "global_8h" ],
    [ "invoices.c", "invoices_8c.html", "invoices_8c" ],
    [ "invoices.h", "invoices_8h.html", "invoices_8h" ],
    [ "lCommand.c", "l_command_8c.html", "l_command_8c" ],
    [ "lCommand.h", "l_command_8h.html", "l_command_8h" ],
    [ "lists.c", "lists_8c.html", "lists_8c" ],
    [ "lists.h", "lists_8h.html", "lists_8h" ],
    [ "main.c", "main_8c.html", "main_8c" ],
    [ "pCommand.c", "p_command_8c.html", "p_command_8c" ],
    [ "pCommand.h", "p_command_8h.html", "p_command_8h" ],
    [ "products.c", "products_8c.html", "products_8c" ],
    [ "products.h", "products_8h.html", "products_8h" ],
    [ "rCommand.c", "r_command_8c.html", "r_command_8c" ],
    [ "rCommand.h", "r_command_8h.html", "r_command_8h" ],
    [ "trees.c", "trees_8c.html", "trees_8c" ],
    [ "trees.h", "trees_8h.html", "trees_8h" ]
];